### ISSUE TITLE
ResistanceGA no longer optimizing with Circuitscape

### ISSUE THREAD

**Issue by jamesryan1896** [wpeterman/ResistanceGA#10]
I am running ResistanceGA on Windows 10 in Rstudio, using R version 3.6.1
I'm trying to optimize using Circuitscape v4.0.5
It had previously been working however it has recently started providing me with an error I cannot seem to fix.

This is the code I am using

![Capture](https://user-images.githubusercontent.com/57244426/68002153-15681900-fcb3-11e9-94bb-03de5f553aab.PNG)

And this is the error message I receive
![Capture2](https://user-images.githubusercontent.com/57244426/68002169-287ae900-fcb3-11e9-97af-fc8eb3c986dc.PNG)

Optimization had previously been working for me, I am unsure why it has stopped. I would optimize using gdist however it typically takes approximately 600 seconds per iteration where Circuitscape previously took approx 90 seconds per iteration.

Are you aware of anything which might cause this error to occur? I have tried already reinstalling ResistanceGA however the error persists. Any help would be greatly appreciated!

Thank you,
James

**Comment by wpeterman** [comment]
Hi James--

Thanks for the email, and sorry for the troubles. I'm not exactly sure what
the issue is. ResistanceGA is trying to write and read files to the temp
directory, so if you have limited access privileges on your computer, this
could be a problem. I have a couple of suggestions.

1) Install the latest development version –
*devtools::install_github('wpeterman/ResistanceGA',
ref = 'julia_dev')*
2) Rather than provide a link to a point file, specify the spatial points
object directly – *CS_Point.File = sample.locales*

Let me know if this resolves your issues.



*Bill Peterman *Assistant Professor
School of Environment and Natural Resources
The Ohio State University
2021 Coffey Road
Columbus, OH 43210-1085
Phone: 614.292.9795
Web Page <https://goo.gl/4Gc15W>
Terrestrial Wildlife Ecology Lab <http://www.twel.osu.edu>

Bill Peterman

**Comment by jamesryan1896** [comment]
Hi Bill,

I have reinstalled both Circuitscape and ResistanceGA and my code appears to be running again. I am not quite sure what changed however it appears to be writing to the temp file correctly now. If I encounter this issue again in the future I will retry using the spatial points object.

Thank you for your response and thank you for this great package ResistanecGA! I will close this issue now
