### ISSUE TITLE
ideas for model performance and validation

### ISSUE THREAD

**Issue by jeffreyhanson** [wpeterman/ResistanceGA#2]
Hi,

I was wondering if you have thought about using _k_-fold cross-validation to assess the performance of optimized resistance landscapes? In each fold, the data would be partitioned into training and test data. The training data would be used to generate a resistance surface, and the test data would be used to evaluate the quality of the resistance surface. This process would be repeated _k_  times using different subsets for training and testing. After running k-fold cross-validation, users could then see how well the resistance landscapes perform, and determine if the optimization process has found a "good enough" model.

Also, I wonder how prone this approach is to over-fitting? Do you have experience with this? By over-fitting I mean that if you included additional surfaces that "in truth" do not affect gene flow, would this approach return non-zero coefficients for these surfaces, since this would slightly improve model fit? If so, I wonder if the MLPE model could be modified to include a regularization term (like Maxent), so users could specify a parameter that penalizes over fitting.  Users could then try several different penalization parameters and identify the best model using something like k-fold cross-validation (eg. like what is done in the [ENMeval R package ](https://cran.r-project.org/web/packages/ENMeval/index.html) for fitting and tuning Maxent models). I haven't used it, but the [glmmLasso package](https://cran.r-project.org/web/packages/glmmLasso/index.html) seems to implement linear mixed effects models with L1 regularization.

Also, [there appears to be some contention about how R^2 values should be calculated for linear mixed effects model](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC2587505/). I think it would be nice if users could specify what R^2 formulation should be used. The [r2glmm R package](https://github.com/bcjaeger/r2glmm) provides several methods for calculating R^2 values for linear mixed effects models, so maybe an argument could be used in `GA.prep` to specify which method should be used?

**Comment by wpeterman** [comment]
Hi Jeff--

Thanks for the email and for the great suggestions. I do think that k-fold
cross-validation could implemented, although I think it would have to more
of a 'pseudo' k-fold, which my miss the point. A true k-fold, where the
entire surface is re-optimized for each fold would likely me too intensive
for most people and applications. It can take days to run a modest number
of surfaces as is, and have to run each 5-10 times might not be tractable
(although it could be informative). In lieu of the full k-fold
re-optimization, a k-fold analysis could be done on the optimized surface
only. I think there might still be value in this. If you evaluate the RMSE
(for example) among the different optimized surfaces, it would provide a
more tangible/relevant statistic describing the predictive power of the
optimized surface predict genetic differentiation. Thoughts?

Unfortunately, I think that over-fitting as you define it is nearly
inevitable with these models. I say this because in most scenarios,
distances is almost always an underlying/contributing factor to the
measured differentiation. As such, even random noise surfaces typically
have a non-zero slope relationship with the measured genetic distance data.
I don't think, however, that the over-fitting comes from the mixed effects
model. Rather, I think it is a result of the genetic algorithm evolving as
best as possible toward an optimal solution.

Thanks for the links to the package with more/different R^2 calculations.
I'll have to look into these, and see if it is worth trying to incorporate
them into my package. Time is limited for me, and any little change, no
matter how straight forward, always results in a lot of time running tests,
checks, and debugging. However, the most recent release of the package
saves the final fitted lmer model objects. As such, it is possible to use
any applicable R^2 method with the final fitted models.

Thanks again for the email!

-Bill-



*Bill Peterman *Assistant Professor
School of Environment and Natural Resources
The Ohio State University
2021 Coffey Road
Columbus, OH 43210-1085
Phone: 614.292.9795
Web Page <https://goo.gl/4Gc15W>
Terrestrial Wildlife Ecology Lab <http://www.twel.osu.edu>

Bill Peterman

**Comment by jeffreyhanson** [comment]
Yeah, I think the pseudo _k_ fold would be useful. This would provide information on whether certain outlier populations were driving the optimisation process since the surface will have poor predictive power for sets of individuals/populations that do not include these outliers. This _post-hoc_ checking could be done by the user after generating the optimised surface, I'll give it a shot and let you know how it goes.

From what I understand, and I may be wrong, the over-fitting comes from the objective (fitness) function. If the optimisation is performed using a statistic that just describes well the model fits the data (eg. the R2 or log-likelihood for a MLPE model), then the optimisation process will find the coefficients that transform the raw surfaces into the resistance surface that explain the most genetic variation. It is using this fitness function that leads to over-fitting. If a different fitness function was used that described how much genetic variation is explained and also penalises for over-fitting then this will avoid resistance surfaces that are over-fit to the genetic data. Does that make sense?

One approach, inspired from [lasso regression](https://www.analyticsvidhya.com/blog/2016/01/complete-tutorial-ridge-lasso-regression-python/), would be to penalise the objective function by how "non-zero" the transformation coefficients are. This would cause the optimisation process to favour solutions that only use non-zero transformation coefficients when they substantially improve the quality of the resistance surface.  Before I suggested using a MLPE with regularisation, but I now think this is wrong since it won't penalise the transformation coefficients. 

So, an example of an objective function that favours solutions that explain variation in genetic distances and penalises for over-fitting might look like this:

<img src="https://latex.codecogs.com/gif.latex?min:&space;-&space;LL&space;&plus;&space;(P&space;\times&space;\sum_{i=0}^{I}&space;|&space;C_i&space;|&space;)" title="min: - LL + (P \times \sum_{i=0}^{I} | C_i | )" />

where _LL_ is log-likelihood, the _P_ is a positive number indicating the penalty for over-fitting, _I_ is the number of transformation coefficients, and _C_ is an array of the transformation coefficients.

- If a low _P_ is used then the optimisation process will favour surfaces that have very high predictive power regardless of the transformation coefficients, and will over-fit the data. Note that setting _P_ to exactly zero is equivalent to minimising by the negative log-likelihood of the model.
- If a very high _P_ is used then the optimisation process will solutions that have near-zero transformation coefficients regardless of how well the surfaces explains genetic variation. 
- Finally, if a moderate/ideal _P_ is used then the optimisation process will favour solutions that have relatively high predictive power and only use non-zero transformation coefficients when they substantially improve the model's predictive power. Thus the resistance surface would not be over-fit to the genetic data.

This approach would only really work when you can evaluate multiple penalties (_P_) and identify the penalty that gives the best model ([eg. as shown here when tuning regularization penalties for MaxEnt](http://onlinelibrary.wiley.com/doi/10.1111/jbi.12227/full)). So, it might not be useful given how long it takes to optimise a single resistance surface (though if we are making comparisons to MaxEnt, [the default penalty/regularization parameter is used in 93 % of studies](http://biorxiv.org/content/early/2016/10/12/080457)). What do you think?

**Comment by wpeterman** [comment]
Hi Jeff--

Thanks for the clear explanation and walk-through of a penalization
parameter could be implemented. I have used ENMTools to tune the
regularization parameter for Maxent in the past. Interesting to think how
this could be applied when fitting MLPE mixed effected models.

One potential challenge to doing cross validation with these models would
be correctly incorporating the random effects. I have not had a chance (and
won't for a while) to see how the models can predict on hold-out data.

Thanks again--Bill

PS--If you're interested/eager to try any of these ideas, by all means,
feel free to do so. I must confess that the coding is rather atrocious as
this project started when my skills were still quite nascent.



*Bill Peterman *Assistant Professor
School of Environment and Natural Resources
The Ohio State University
2021 Coffey Road
Columbus, OH 43210-1085
Phone: 614.292.9795
Web Page <https://goo.gl/4Gc15W>
Terrestrial Wildlife Ecology Lab <http://www.twel.osu.edu>

Bill Peterman

**Comment by jeffreyhanson** [comment]
I'll close this issue, and let you know how it goes as things develop.
